name: prototipo_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_cube: ^0.1.1
  video_player: ^2.9.5
  http: ^0.13.6
   

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/video/intro-screen.mp4
    - assets/3d/
    